// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package Qnet

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "Qnet", asset.ModuleFieldsPri, AssetQnet); err != nil {
		panic(err)
	}
}

// AssetQnet returns asset data.
// This is the base64 encoded gzipped contents of module/Qnet.
func AssetQnet() string {
	return "eJzMlEFugzAQRfecYpR9LsCiN6jUngC5+IdYMbY1M7Th9hUoSR3qqsmipKzgz+fzYIbZ0gFjTa8BWhGpU4+aNtPlpiKykJZdUhdDTU8VEc1Oeo528KiIdg7eSj1XthRMj0vWdOiYUFPHcUgnpZB4nZInmbaFyEVe3P3iYQRkrM31zI2j6dP0PpnzpGWu74wlpC8oRh8Vjcvd95LdynamO2D8iGwLNIOAm+l0RRrFUQso6lahOD+uh+6j/R9NYP/4z79XTc07WJbpf0vjY+iKf4mkGARNG+2as/kDzlu0YyMIuiLKcqWUlkpGOCrkqnI/3+2Ev3ZvB2bw46fadOs2bcb4DAAA//+OdPyr"
}
